# Servidor e Contexto
server.port=8080
server.servlet.context-path=/api/v1

# Nome da Aplicação
spring.application.name=ms-pedidos

# JAVA 21: Ativação de Virtual Threads
spring.threads.virtual.enabled=true

# Banco de Dados (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Kafka Producer (Mensageria)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.properties.spring.json.trusted.packages=*

# Observabilidade (Actuator + Prometheus)
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true

# Resiliência (Resilience4j)
resilience4j.circuitbreaker.instances.kafkaProducer.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.kafkaProducer.slidingWindowSize=10
resilience4j.circuitbreaker.instances.kafkaProducer.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.kafkaProducer.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.kafkaProducer.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.kafkaProducer.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.kafkaProducer.failureRateThreshold=50
